export const CardList = [
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: 'http://techslides.com/demos/sample-videos/small.mp4',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=1',
      'https://picsum.photos/430/320?random=2',
      'https://picsum.photos/430/320?random=3',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: 'http://techslides.com/demos/sample-videos/small.mp4',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=3',
      'https://picsum.photos/430/320?random=4',
      'https://picsum.photos/430/320?random=5',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=4',
      'https://picsum.photos/430/320?random=5',
      'https://picsum.photos/430/320?random=6',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=5',
      'https://picsum.photos/430/320?random=6',
      'https://picsum.photos/430/320?random=7',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=0',
      'https://picsum.photos/430/320?random=1',
      'https://picsum.photos/430/320?random=2',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=1',
      'https://picsum.photos/430/320?random=2',
      'https://picsum.photos/430/320?random=3',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=2',
      'https://picsum.photos/430/320?random=3',
      'https://picsum.photos/430/320?random=4',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=3',
      'https://picsum.photos/430/320?random=4',
      'https://picsum.photos/430/320?random=5',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=4',
      'https://picsum.photos/430/320?random=5',
      'https://picsum.photos/430/320?random=6',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=5',
      'https://picsum.photos/430/320?random=6',
      'https://picsum.photos/430/320?random=7',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=0',
      'https://picsum.photos/430/320?random=1',
      'https://picsum.photos/430/320?random=2',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=1',
      'https://picsum.photos/430/320?random=2',
      'https://picsum.photos/430/320?random=3',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=2',
      'https://picsum.photos/430/320?random=3',
      'https://picsum.photos/430/320?random=4',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=3',
      'https://picsum.photos/430/320?random=4',
      'https://picsum.photos/430/320?random=5',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=4',
      'https://picsum.photos/430/320?random=5',
      'https://picsum.photos/430/320?random=6',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=5',
      'https://picsum.photos/430/320?random=6',
      'https://picsum.photos/430/320?random=7',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=0',
      'https://picsum.photos/430/320?random=1',
      'https://picsum.photos/430/320?random=2',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=1',
      'https://picsum.photos/430/320?random=2',
      'https://picsum.photos/430/320?random=3',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=2',
      'https://picsum.photos/430/320?random=3',
      'https://picsum.photos/430/320?random=4',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=3',
      'https://picsum.photos/430/320?random=4',
      'https://picsum.photos/430/320?random=5',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=4',
      'https://picsum.photos/430/320?random=5',
      'https://picsum.photos/430/320?random=6',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=5',
      'https://picsum.photos/430/320?random=6',
      'https://picsum.photos/430/320?random=7',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=0',
      'https://picsum.photos/430/320?random=1',
      'https://picsum.photos/430/320?random=2',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=1',
      'https://picsum.photos/430/320?random=2',
      'https://picsum.photos/430/320?random=3',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=2',
      'https://picsum.photos/430/320?random=3',
      'https://picsum.photos/430/320?random=4',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=3',
      'https://picsum.photos/430/320?random=4',
      'https://picsum.photos/430/320?random=5',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=4',
      'https://picsum.photos/430/320?random=5',
      'https://picsum.photos/430/320?random=6',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=5',
      'https://picsum.photos/430/320?random=6',
      'https://picsum.photos/430/320?random=7',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=0',
      'https://picsum.photos/430/320?random=1',
      'https://picsum.photos/430/320?random=2',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=1',
      'https://picsum.photos/430/320?random=2',
      'https://picsum.photos/430/320?random=3',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=2',
      'https://picsum.photos/430/320?random=3',
      'https://picsum.photos/430/320?random=4',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=3',
      'https://picsum.photos/430/320?random=4',
      'https://picsum.photos/430/320?random=5',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=4',
      'https://picsum.photos/430/320?random=5',
      'https://picsum.photos/430/320?random=6',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=5',
      'https://picsum.photos/430/320?random=6',
      'https://picsum.photos/430/320?random=7',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=0',
      'https://picsum.photos/430/320?random=1',
      'https://picsum.photos/430/320?random=2',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=1',
      'https://picsum.photos/430/320?random=2',
      'https://picsum.photos/430/320?random=3',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=2',
      'https://picsum.photos/430/320?random=3',
      'https://picsum.photos/430/320?random=4',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=3',
      'https://picsum.photos/430/320?random=4',
      'https://picsum.photos/430/320?random=5',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=4',
      'https://picsum.photos/430/320?random=5',
      'https://picsum.photos/430/320?random=6',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=5',
      'https://picsum.photos/430/320?random=6',
      'https://picsum.photos/430/320?random=7',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=0',
      'https://picsum.photos/430/320?random=1',
      'https://picsum.photos/430/320?random=2',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=1',
      'https://picsum.photos/430/320?random=2',
      'https://picsum.photos/430/320?random=3',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=2',
      'https://picsum.photos/430/320?random=3',
      'https://picsum.photos/430/320?random=4',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=3',
      'https://picsum.photos/430/320?random=4',
      'https://picsum.photos/430/320?random=5',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=4',
      'https://picsum.photos/430/320?random=5',
      'https://picsum.photos/430/320?random=6',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=5',
      'https://picsum.photos/430/320?random=6',
      'https://picsum.photos/430/320?random=7',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=0',
      'https://picsum.photos/430/320?random=1',
      'https://picsum.photos/430/320?random=2',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=1',
      'https://picsum.photos/430/320?random=2',
      'https://picsum.photos/430/320?random=3',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=2',
      'https://picsum.photos/430/320?random=3',
      'https://picsum.photos/430/320?random=4',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=3',
      'https://picsum.photos/430/320?random=4',
      'https://picsum.photos/430/320?random=5',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=4',
      'https://picsum.photos/430/320?random=5',
      'https://picsum.photos/430/320?random=6',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=5',
      'https://picsum.photos/430/320?random=6',
      'https://picsum.photos/430/320?random=7',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=0',
      'https://picsum.photos/430/320?random=1',
      'https://picsum.photos/430/320?random=2',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=1',
      'https://picsum.photos/430/320?random=2',
      'https://picsum.photos/430/320?random=3',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=2',
      'https://picsum.photos/430/320?random=3',
      'https://picsum.photos/430/320?random=4',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=3',
      'https://picsum.photos/430/320?random=4',
      'https://picsum.photos/430/320?random=5',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=4',
      'https://picsum.photos/430/320?random=5',
      'https://picsum.photos/430/320?random=6',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=5',
      'https://picsum.photos/430/320?random=6',
      'https://picsum.photos/430/320?random=7',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=0',
      'https://picsum.photos/430/320?random=1',
      'https://picsum.photos/430/320?random=2',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=1',
      'https://picsum.photos/430/320?random=2',
      'https://picsum.photos/430/320?random=3',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=2',
      'https://picsum.photos/430/320?random=3',
      'https://picsum.photos/430/320?random=4',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=3',
      'https://picsum.photos/430/320?random=4',
      'https://picsum.photos/430/320?random=5',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=4',
      'https://picsum.photos/430/320?random=5',
      'https://picsum.photos/430/320?random=6',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=5',
      'https://picsum.photos/430/320?random=6',
      'https://picsum.photos/430/320?random=7',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=0',
      'https://picsum.photos/430/320?random=1',
      'https://picsum.photos/430/320?random=2',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=1',
      'https://picsum.photos/430/320?random=2',
      'https://picsum.photos/430/320?random=3',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=2',
      'https://picsum.photos/430/320?random=3',
      'https://picsum.photos/430/320?random=4',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=3',
      'https://picsum.photos/430/320?random=4',
      'https://picsum.photos/430/320?random=5',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=4',
      'https://picsum.photos/430/320?random=5',
      'https://picsum.photos/430/320?random=6',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  },
  {
    slug: 'details',
    defaultImg: 'https://picsum.photos/430/320?random=',
    slideImages: [
      'https://picsum.photos/430/320?random=5',
      'https://picsum.photos/430/320?random=6',
      'https://picsum.photos/430/320?random=7',
    ],
    title: 'La Roche Posay',
    subTitle: 'Anthelios',
    video: '',
  }
]